#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact 'ddc';
use Music::Duration::Partition;

my $mdp = Music::Duration::Partition->new(
  size   => 8,
  pool   => [qw(hn qn tqn)],
  groups => [0, 0, 3],
);

my $motif = $mdp->motif;
warn(__PACKAGE__,' ',__LINE__," MARK: ",ddc($motif));
